[General]
SyntaxVersion=2
BeginHotkey=122
BeginHotkeyMod=0
PauseHotkey=0
PauseHotkeyMod=0
StopHotkey=123
StopHotkeyMod=0
RunOnce=1
EnableWindow=
MacroID=2f87ff29-19cc-404b-836e-7d9b6ccf8ac4
Description=按下熱鍵，訪問腳本倉庫，上千腳本任您下載
Enable=0
AutoRun=0
[Repeat]
Type=0
Number=1
[SetupUI]
Type=2
QUI=
[Relative]
SetupOCXFile=
[Comment]

[Script]
//訪問按鍵精靈官網提供的源碼庫，學習腳本製作技巧
Call RunApp("http://www.vrbrothers.com/cn/qmacro/qcodelib/Browse/Index")
